### ISSUE TITLE
Poor hinting on recent Chrome

### ISSUE THREAD

**Issue by bblack** [github/octicons#42] opened 2015-03-20 20:11 UTC
Not sure whether to put this issue on octicons or github.com itself, but on recent versions of Chrome (42.0.2311.50 beta (64-bit) presently) on Mac OSX Mavericks, I'm seeing that if the page is an odd number of pixels wide, the octicons look like they don't align well with the pixel grid horizontally:

![screen shot 2015-03-20 at 4 11 15 pm](https://cloud.githubusercontent.com/assets/1072131/6760068/cb566174-cf1b-11e4-92dc-c3bb2ac04d6e.png)

**Comment by cameronmcefee** [comment] 2015-03-20 22:28
From testing it looks like it varies depending on the pixel width of the browser window >.< This isn't the first time a font rendering bug has come up in Chrome and they usually get fixed pretty quick. I'm going to close this for now under the assumption that this really is a bug, however feel free to reopen if you find a solution/it turns out to be the future.

**Closed by cameronmcefee** 2015-03-20 22:28 UTC

**Comment by nanoant** [comment] 2015-11-16 23:02
@cameronmcefee Please re-open this. I think I've just hit the tip of an iceberg. It seems that every major web browser does NOT pixel align fonts horizontally (despite hinting settings) if the browser window is odd pixel wide. This happens on OS X but also on Windows (IE11, IE10). So it is not solely Chrome bug.

It can be observed when opening https://octicons.github.com/ and modifying slightly size of your browser window. Watching carefully icons we can see that when browser width changes by 1 pixel then icons become blurry and get crips again with next pixel change.

Actually it happens too with even number of pixels wide, but when layout causes some non-integer widths of some elements, see 4 columns of this https://fortawesome.github.io/Font-Awesome/icons/ - some icon columns as crisp & sharp, some are blurry.

This cannot be simply bug in every browser. I guess this may be a consequence of two things:

1. CSS and browser layout metrics seems to be fractional, so when page container have exact left & right margin and windows size if odd then your page container (div) will start at half-pixel
2. Your font hinting is unable to force browser to start rendering font on full-pixel when container is half pixel

So it would be great if anyone can shed some light on this issue, what is the real origin of this problem. Especially when Octicons were advertised as pixel-perfect, but apparently they are not in current situation.

And the reason I found this issue here was I just recently noticed on my non retina iMac that some GitHub site icons seems to be bit blurry, while they are never blurry on Retina, not because the higher resolution, but because on Retina window size is still measured in integer points = 2x pixels. So when some div starts at half logical pixel, it actually starts at full physical pixel on Retina.

**Comment by cameronmcefee** [comment] 2015-11-25 17:55
The fuzzy-at-all-sizes sounds like a css thing for sure. @aaronshekey has there been any sort of layout work done recently that might be force-centering the glyphs?

**Comment by aaronshekey** [comment] 2015-11-26 22:47
Nope, no CSS changes. As far as I'm aware, the blurriness recently arrived with Safari 9. Prior to that, these were blurry in Chrome alone. I believe this is a browser issue but don't know if there are any workarounds outside of switching to SVG for rendering.

**Comment by cameronmcefee** [comment] 2015-11-30 18:05
:hankey:. Given other priorities at the moment, I'm gonna leave this closed for now unless we can find an example of an icon font that has solved the issue that I can reverse engineer.

**Comment by nanoant** [comment] 2015-12-17 21:02
Dear GitHubbers, I found our this to be a WebKit bug, probably ported to Chrome (which is WebKit fork). The regression was introduced to WebKit last year, today I have created WebKit bug report for it:

https://bugs.webkit.org/show_bug.cgi?id=152393

**Comment by nanoant** [comment] 2015-12-17 22:14
Decided to hunt down this bug at Chrome/Chromium/Blink too:

https://code.google.com/p/chromium/issues/detail?id=570812

I encourage everyone to post on Chromium & WebKit issue links above some comments about this issue. Let's have icon fonts usable again.
